<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-medium text-emerald-700">Scholarship Chairman</p><h2 class="text-xl font-semibold">Consolidate {{ $masterlist->file_name }}</h2></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8"><x-status-alerts/>@if($errors->has('release'))<p class="rounded bg-red-50 p-3 text-red-900">{{ $errors->first('release') }}</p>@endif
        <section class="grid gap-3 md:grid-cols-2 lg:grid-cols-4">@foreach($campusProgress as $item)<article class="rounded-lg bg-white p-4 shadow"><h3 class="font-bold">{{ $item['campus']->name }}</h3><p class="text-sm text-gray-600">{{ $item['records'] }} records</p><p class="mt-2 font-semibold text-emerald-800">{{ Str::headline($item['status']) }}</p></article>@endforeach</section>
        <section class="rounded-lg bg-white p-5 shadow"><h2 class="text-lg font-bold">Final Qualified Beneficiaries</h2><div class="mt-4 overflow-x-auto"><table class="min-w-full"><thead><tr class="border-b"><th class="p-3 text-left">Beneficiary</th><th class="p-3 text-left">Campus</th><th class="p-3 text-left">Enrollment</th><th class="p-3 text-left">COR</th></tr></thead><tbody>@forelse($masterlist->records()->with('campus')->where('final_qualification_status', 'qualified')->oldest('id')->get() as $record)<tr class="border-b"><td class="p-3">{{ $record->student_name }}</td><td class="p-3">{{ $record->campus?->name }}</td><td class="p-3">{{ Str::headline($record->final_enrollment_status) }}</td><td class="p-3">{{ Str::headline($record->final_cor_status) }}</td></tr>@empty<tr><td colspan="4" class="p-6 text-center">No beneficiaries qualified.</td></tr>@endforelse</tbody></table></div></section>
        @if(in_array($masterlist->status, ['ready_for_consolidation', 'released'], true))<a class="inline-flex rounded-md bg-emerald-800 px-4 py-3 font-semibold text-white" href="{{ route('chairman.masterlists.export', $masterlist) }}">Export Final Qualified CSV</a>@endif
        @if($masterlist->status !== 'released')<form method="POST" action="{{ route('chairman.masterlists.release', $masterlist) }}">@csrf<x-confirm-submit message="Mark this verified list as forwarded to the external Scholarship Agency?">Mark as Forwarded</x-confirm-submit></form>@endif
    </div></div>
</x-app-layout>
