<x-app-layout>
    <x-slot name="header">
        <div>
            <p class="text-sm font-medium text-emerald-700">{{ __('Administrator') }}</p>
            <h2 class="text-xl font-semibold leading-tight text-gray-900">
                {{ __('Generated Certificate History') }}
            </h2>
        </div>
    </x-slot>

    <div class="py-10">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div class="overflow-hidden rounded-lg bg-white shadow-sm ring-1 ring-gray-200">
                <div class="overflow-x-auto">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th class="px-6 py-3 text-left text-xs font-semibold uppercase text-gray-600">{{ __('Certificate No.') }}</th>
                                <th class="px-6 py-3 text-left text-xs font-semibold uppercase text-gray-600">{{ __('Student') }}</th>
                                <th class="px-6 py-3 text-left text-xs font-semibold uppercase text-gray-600">{{ __('Request') }}</th>
                                <th class="px-6 py-3 text-left text-xs font-semibold uppercase text-gray-600">{{ __('Generated By') }}</th>
                                <th class="px-6 py-3 text-left text-xs font-semibold uppercase text-gray-600">{{ __('Generated') }}</th>
                                <th class="px-6 py-3 text-right text-xs font-semibold uppercase text-gray-600">{{ __('Action') }}</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200 bg-white">
                            @forelse ($certificates as $certificate)
                                <tr>
                                    <td class="whitespace-nowrap px-6 py-4 text-sm font-semibold text-gray-950">
                                        {{ $certificate->certificate_number }}
                                    </td>
                                    <td class="px-6 py-4 text-sm text-gray-900">
                                        <div class="font-semibold">{{ $certificate->certificateRequest->student->fullName() }}</div>
                                        <div class="text-xs text-gray-500">{{ $certificate->certificateRequest->student->student_id_number }}</div>
                                    </td>
                                    <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-700">
                                        #{{ $certificate->certificate_request_id }}
                                    </td>
                                    <td class="px-6 py-4 text-sm text-gray-700">
                                        {{ $certificate->generatedBy?->name ?? __('System') }}
                                    </td>
                                    <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-700">
                                        {{ $certificate->generated_at?->format('M d, Y h:i A') ?? $certificate->created_at->format('M d, Y h:i A') }}
                                    </td>
                                    <td class="whitespace-nowrap px-6 py-4 text-right text-sm">
                                        <a href="{{ route('admin.certificates.download', $certificate) }}" class="font-semibold text-emerald-800 hover:text-emerald-950">
                                            {{ __('Download PDF') }}
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6" class="px-6 py-12 text-center text-sm text-gray-600">
                                        {{ __('No generated certificates yet.') }}
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

                @if ($certificates->hasPages())
                    <div class="border-t border-gray-200 px-6 py-4">
                        {{ $certificates->links() }}
                    </div>
                @endif
            </div>
        </div>
    </div>
</x-app-layout>
